---
title: "NYC Restaurant Inspection Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
```

Inputs {.sidebar}
-------------------------------------

This flexdashboard uses plot.ly to visualize NYC restaurant inspection data. The data set used was specific to Jeff Goldsmith's Data Science I fall 2018 course at Columbia University's Mailman School of Public Health, but an updated version can be publicly found on [NYC Open Data](https://dev.socrata.com/foundry/data.cityofnewyork.us/9w7m-hzhe). 

More information about the data set can be found [here](http://p8105.com/dataset_restaurant_inspections.html). 

Every regulation that a restaurant fails to comply with earns that restaurant points according to a defined scoring scheme. The total number of points at the conclusion of an inspection are converted into grades. The more points a restaurant accumulates, the worse the grade that restaurant is given.

Return to my website [here](index.html).

Column {data-width=500}
-----------------------------------------------------------------------

### Scores of most popular restaurant types

```{r}
popular_cuisine =
  rest_inspec %>% 
  count(cuisine_description, sort = TRUE) %>% 
  top_n(8) %>% 
  select(cuisine_description)

inner_join(rest_inspec, popular_cuisine,
             by = "cuisine_description") %>% 
  mutate(cuisine_description = fct_reorder(cuisine_description, score)) %>% 
  plot_ly(
    x = ~cuisine_description,
    y = ~score,
    split = ~cuisine_description,
    type = 'violin',
    box = list(
      visible = T,
    colors = "Set2"),
    meanline = list( 
      visible = T
    )
  ) %>% 
  layout(
    xaxis = list(title = "cuisine type"),
    legend = list(orientation = 'h', yanchor = 'bottom', y = -1.2)
  )
```

Column {data-width=500}
-----------------------------------------------------------------------

### Distribution of scores per borough by year

```{r}
rest_inspec %>% 
  plot_ly(x = ~score, type = 'histogram', color = ~boro, alpha = 0.6,
          transforms = list(
            list(
              type = 'filter',
              target = ~year,
              operation = '=',
              value = unique(rest_inspec$year)[1]
              )
            )
          ) %>% 
  layout(barmode = "overlay", yaxis = list(title = "count"),
    updatemenus = list(
      list(
        type = 'dropdown',
        active = 0,
        buttons = list(
          list(method = "restyle",
            args = list("transforms[0].value", unique(rest_inspec$year)[1]),
            label = unique(rest_inspec$year)[1]),
          list(method = "restyle",
            args = list("transforms[0].value", unique(rest_inspec$year)[2]),
            label = unique(rest_inspec$year)[2]),
          list(method = "restyle",
            args = list("transforms[0].value", unique(rest_inspec$year)[3]),
            label = unique(rest_inspec$year)[3]),
          list(method = "restyle",
            args = list("transforms[0].value", unique(rest_inspec$year)[4]),
            label = unique(rest_inspec$year)[4]),
          list(method = "restyle",
            args = list("transforms[0].value", unique(rest_inspec$year)[5]),
            label = unique(rest_inspec$year)[5])
          )
        )
      )
    )
```

### Distribution of grades by borough

```{r}
rest_inspec %>% 
  count(boro, grade) %>% 
  mutate(
    boro = fct_reorder(boro, n),
    grade = case_when(
    grade == "A" ~ "A",
    grade == "B" ~ "B",
    grade == "C" ~ "C",
    grade == "Not Yet Graded" ~ "Ungraded",
    grade == "P" ~ "Ungraded",
    grade == "Z" ~ "Ungraded"
    )
  ) %>% 
  plot_ly(x = ~grade, y = ~n, color = ~boro, type = "bar") %>% 
  layout(yaxis = list(title = "count"), barmode = 'stack')
```

